title: "これからはじめるdiscord.py(仮)"
summary: "Python初心者にもわかりやすく解説したdiscord.py入門書。"
topics: ["discord", "python"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - example1
  - example2
